const START_SPINNING_TIME = 2600
const CONTINUE_SPINNING_TIME = 750
const STOP_SPINNING_TIME = 8000
const DEFAULT_SPIN_DURATION = 1.0
const DEFAULT_VALUE = [1]
const DEFAULT_LABEL = ["placeholder"]
const DEFAULT_ROTATION = 90
const DEFAULT_COLOR = ["#000000"]

module.exports = {
    START_SPINNING_TIME,
    CONTINUE_SPINNING_TIME,
    STOP_SPINNING_TIME,
    DEFAULT_SPIN_DURATION,
    DEFAULT_VALUE,
    DEFAULT_LABEL,
    DEFAULT_ROTATION,
    DEFAULT_COLOR,
};